### ISSUE TITLE
save complex filters/queries to easy switch between most used ones?

### ISSUE THREAD

**Issue by zeltak** [christianwannerstedt/obsidian-tags-overview#22]
Hi again!

so as stated before I LOVE using tags-overview! I will use it heavily going forward now with yaml property support and was wondering if I could ask to add the ability to save (Ala bookmark or list) complex filters/queries I use?

for example when I filter by tag then properly etc like this

![CleanShot 2024-01-08 at 08 28 28@2x](https://github.com/christianwannerstedt/obsidian-tags-overview/assets/498410/bf98c4a6-39f9-4872-a612-80a7f8d878dd)

I would like to quick jump/load different sets of filters, does that make sense?

thx so much

Z

**Comment by christianwannerstedt** [comment]
That does make sense indeed :), and I've actually been doing something similar with another project I've been working with. So I can definitely try to add it to this plugin as well.

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([1.0.4](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.4)). There is now a save icon in the top left corner where you can find this functionality. (The top area looks a bit empty now but I have plans to add more icons there further down the road..)

I will also add a section to the Readme, explaining the save/load functionality shortly.
