### ISSUE TITLE
Available also for iOS?

### ISSUE THREAD

**Issue by JoKo1959** [christianwannerstedt/obsidian-tags-overview#5]
Very useful plugin, thank you! Currently, this plugin does not work with the iOS Obsidian mobile app. It would be fantastic if your plugin was also available for iOS.

**Comment by christianwannerstedt** [comment]
Thanks for your feedback! This have been fixed in the latest release ([0.1.5](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.5)), so the plugin should now be functional in the mobile app as well.

At the moment, no special adaptations or similar have been made to the mobile interface, but there might be some improvements further down the road.

**Comment by JoKo1959** [comment]
Thank you, this now works perfectly in iOS
