### ISSUE TITLE
Support for "Front Matter Title" Plugin

### ISSUE THREAD

**Issue by cervera-queiroz** [christianwannerstedt/obsidian-tags-overview#6]
Hi there,

Great plugin, been using for a few days and loving it. I'm currently naming my notes with an unique id (Zettelkasten method, e.g. 20231022173230) and been using the "Front Matter Title" plugin to use the "title" yaml to identify my notes in the explorer/search areas. Would it be possible to have the possibility to display an yaml property as the name of the file?

Thanks!

**Comment by christianwannerstedt** [comment]
Hey,
Thanks for your feedback! I think that sounds like a good idea, I've had some thoughts on how it would be possible to use front matter in the plugin, both for filtering and formatting. So I hope this is something I have time to look at soon.

**Comment by christianwannerstedt** [comment]
There has now been an update, where it is possible to choose which info should be displayed for each file. This update only affects the list that is displayed if you have selected list view (instead of compact), but it means that you have significantly more control over the appearance. If you update the plugin to the latest version ([0.1.7](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.7)) you'll find these new settings in the plugin settings page.

In addition to some standard columns, you can also choose to use front matter properties, which I hope would do the trick for you, as you can now replace the standard column "File name" with the front matter"Title" property.
